Changes from review https://github.com/integritee-network/worker/pull/594
integritee-network/teeracle pull request #11
Opened 2022-01-11 17:37 UTC by echevrier

2022-01-12 13:08 UTC, haerdib requested changes
Much better now, thanks! Some small issues though

2022-01-12 13:08 UTC, haerdib commented on app-libs/exchange-oracle/src/coingecko.rs
> +			Some(r) => Ok(U32F32::from_num(r)),
Don't use `U32F32` here, you're returning the type `ExchangeRate`

2022-01-12 13:08 UTC, haerdib commented on app-libs/exchange-oracle/src/coingecko.rs
> +		let zero = U32F32::from_num(0);
Use `ExchangeRate` type

2022-01-12 13:08 UTC, haerdib commented on app-libs/exchange-oracle/src/coingecko.rs
> +		assert!(dot_usd > zero);
Why only `dot_usd` and not also `bit_chf?`

2022-01-12 13:08 UTC, haerdib commented on service/src/cli.yml
> +                help: update exchange rate interval. In syntax accepted by parse_duration. Ex 5 seconds 15 minutes 2 hours 1 days or 5s15m2h1d
```suggestion
                help: Set the update exchange rate interval. Accepted Syntax: <5 seconds 15 minutes 2 hours 1 days> or short <5s15m2h1d>
```

2022-01-12 13:08 UTC, haerdib commented on service/src/main.rs
> +			.unwrap_or_else(|e| panic!("Interval parsing error {:?}", e));
I think it's much better and simpler now! Thanks for bearing with me here. ❤️

2022-01-12 15:26 UTC, echevrier commented on app-libs/exchange-oracle/src/coingecko.rs
> +		assert!(dot_usd > zero);
To shorten the test. The important test is` assert_eq!((dot_usd / bit_usd).round(), (dot_chf / bit_chf).round());`

2022-01-12 15:28 UTC, echevrier commented on service/src/cli.yml
> +                help: update exchange rate interval. In syntax accepted by parse_duration. Ex 5 seconds 15 minutes 2 hours 1 days or 5s15m2h1d
There are other possible formats: https://docs.rs/parse_duration/latest/parse_duration/index.html#syntax. So I will add Example of accepted syntax <5 seconds 15 minutes 2 hours 1 days> or short <5s15m2h1d>

2022-01-12 15:51 UTC, haerdib commented on app-libs/exchange-oracle/src/coingecko.rs
> +		assert!(dot_usd > zero);
Makes sense. But why leave this one?

2022-01-12 15:55 UTC, echevrier commented on app-libs/exchange-oracle/src/coingecko.rs
> +		assert!(dot_usd > zero);
To ensure that at least one is positive. The method get_exchange_rate could be wrong and return a negative rate. I all are negative, then the result of the dot_usd / bit_usd would be positive

2022-01-12 16:22 UTC, haerdib commented on app-libs/exchange-oracle/src/coingecko.rs
> +		assert!(dot_usd > zero);
Could you add this as a comment then? Otherwise, the next time we'll look at it, we have forgotten the reasoning behind this.

2022-01-18 08:15 UTC, haerdib approved these changes
LGTM, thanks for the adaptions :)

2022-01-18 08:19 UTC, merged